server:
  port: ${SERVER_PORT:8762}

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888/"
  profiles:
    active: default