server:
  port: ${SERVER_PORT:9093}
spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888/"
  profiles:
    active: default